### ISSUE TITLE
STM32G0B1xx CanBoot with can possible?

### ISSUE THREAD

**Issue by Raabi91** [Arksine/CanBoot#28] opened 2022-06-08 17:34 UTC
hi 
Btt has with his Ebb board 1.1 switched to STM32G0B1xx is it possible to use this chip also with CanBoot with changes. the firmware upload via can was is very pleasant and you do not always have to press the small buttons for the dfu mode

and great work

**Comment by Arksine** [comment] 2022-06-22 21:05
Sorry for the delay, I missed the notification for this issue.  It should be possible to add fdcan support in CanBoot to support flashing the G0 over CanBus.  I have plans to add it, however I want to hold off a bit as there have been some recent changes to Klipper's canbus code and I'd like to make sure it is settled before merging it in CanBoot.

**Comment by w35t13** [comment] 2022-06-24 07:56
awaiting this aswell

**Comment by TheGregV2** [comment] 2022-06-27 09:07
+1 for G0B1 support

**Comment by lgraak** [comment] 2022-06-28 19:53
this would be great

**Comment by Arksine** [comment] 2022-06-30 00:05
PR #33 attempts to add support for the G0.  It builds, however I can't test it so if anyone here wants to give it a try it would be appreciated.

**Comment by Raabi91** [comment] 2022-06-30 19:45
@Arksine I have tried canboot can also flash it. but as soon as I bersuche via flash can to insatlieren an image of klipper comes the following error.

when i use :

`python3 scripts/flash_can.py -i can0 -f ~/klipper/out/klipper.bin -u "myuuid" `

in canboot folder i got this:


```
Sending bootloader jump command...
Resetting all bootloader node IDs...
Checking for canboot nodes...
ERROR:root:Can Flash Error
Traceback (most recent call last):
  File "scripts/flash_can.py", line 609, in main
    loop.run_until_complete(sock.run(intf, uuid, fpath))
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "scripts/flash_can.py", line 461, in run
    f"Unable to find node matching UUID: {uuid:06x}"
FlashCanError: Unable to find node matching UUID: "myuuid"
```


when i use :

`python3 lib/canboot/flash_can.py -i can0 -f ~/klipper/out/klipper.bin -u "myuuid" `

in klipper folder i got this:


```
Sending bootloader jump command...
Resetting all bootloader node IDs...
Checking for canboot nodes...
Detected UUID: "myuuid", Application: CanBoot
Attempting to connect to bootloader
CanBoot Connected
Protocol Version: 1.0.0
Block Size: 64 bytes
Application Start: 0x8002000
MCU type: stm32g0b1xx
Verifying canbus connection
ERROR:root:Can Flash Error
Traceback (most recent call last):
  File "lib/canboot/flash_can.py", line 603, in main
    loop.run_until_complete(sock.run(intf, uuid, fpath))
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "lib/canboot/flash_can.py", line 468, in run
    await flasher.verify_canbus_uuid(uuid)
  File "lib/canboot/flash_can.py", line 109, in verify_canbus_uuid
    ret = await self.send_command('GET_CANBUS_ID')
  File "lib/canboot/flash_can.py", line 187, in send_command
    % (cmdname))
FlashCanError: Error sending command [GET_CANBUS_ID] to Can Device

```

**Comment by Arksine** [comment] 2022-06-30 21:11
The scripts shouldn't be different, so the most likely scenario is that can frames were dropped on the first attempt to flash.  I presume you have previously run Klipper on the device without issue?

Unfortunately I don't have this device, so I can't debug it.  However the fdcan code comes straight from Klipper, so it should drop in and work.

**Comment by NAPCAL** [comment] 2022-06-30 21:12
Run this first to see if your device is on the can bus.
Stop the klipper service.
python3 /home/pi/CanBoot/scripts/flash_can.py -q
You should see the CAN bus ID for your device.

python3 /home/pi/CanBoot/scripts/flash_can.py -u "your can bus id"

Note: the Python script defaults to can0 and /home/pi/klipper/out/klipper.bin

**Comment by incogizmo** [comment] 2022-07-01 00:11
I have EBB36 v1.1.
Flashed the dev branch and was able to then flash Klipper update via CAN.

**Comment by Raabi91** [comment] 2022-07-01 13:56
> Thanks for the feedback @incogizmo . With one working instance I suspect that @Raabi91 is dealing with a general canbus issue.

i take back my errors the only error what was sits once again in front of the screen. i have veregesen to switch to the dev-canbus branches was already quite late. just tried everything again also here everything runs now

**Comment by Arksine** [comment] 2022-07-01 14:38
Thanks Raabi, sounds like interference was causing the issue.

**Comment by cristianku** [comment] 2022-07-01 22:33
> PR #33 attempts to add support for the G0.  It builds, however I can't test it so if anyone here wants to give it a try it would be appreciated.

I can test it . I have both ebb42 and ebb36 both with G0

**Comment by Arksine** [comment] 2022-07-01 23:15
Thanks.  Several users have reported success with the G0 and I have detected no regressions so I merged the PR.  However please feel free to test and leave feedback if you would like.  I'll leave this issue open for a bit for additional feedback.

**Comment by cristianku** [comment] 2022-07-02 08:15
Before I am going to try , can you please tell if the Klipper in menuconfig should be with or without boot loader ? Without canboot I am making it without boot loader ...

**Comment by cristianku** [comment] 2022-07-02 08:32
Ebb36 1.1 : I have successfully installed canboot using stm32 programmer ( erasing full chip before since it was installed with Klipper ) and I have put PA14 as status led . 

**flash_can.py -q ** has found the UUID on the can bus ( ebb36 and U2c are connected through molex ) 

Now I am going to install Klipper via command line through can

**Comment by cristianku** [comment] 2022-07-02 08:42
pi@optimus:~/klipper_ebb36 $ python3 ~/CanBoot/scripts/flash_can.py -q
Resetting all bootloader node IDs...
Checking for canboot nodes...
Detected UUID: 4b2874ce036b, Application: Klipper
Query Complete

**Comment by TheGregV2** [comment] 2022-07-02 09:08
mcu EBBCan(stm32g0b1xx)
Version: v0.10.0-508-g1636a975
Load: 0.02, Awake: 0.00, Freq: 64 MHz,

Working fine at my side.
I've followed this video: https://youtu.be/_FELCN8CbWA
Just replaced CAN communication assignement on PB0/PB1 as specified by Bigtreetech in their manual

**Comment by gargamel778** [comment] 2022-07-02 17:41
I'm late to the party, but I've just flashed CanBoot on my v1.1 EBB36. The process was relatively simple - used STM32 CubeProgrammer from a PC to erase and flash the board over USB with the CanBoot binary, then flashed klipper over canbus from my Pi.

Thanks @Arksine and the rest who tested it!

**Comment by Arksine** [comment] 2022-07-06 23:12
@lgraak  The canbus pins depend on the board.  Generally the board documentation (schematic/pinout) will let you know which pins are used for the canbus.

Since the feedback on this has been positive, I'll go ahead and close this issue.  Thanks all for testing.

**Closed by Arksine** 2022-07-06 23:12 UTC
